
const sigungu = [{
  si: {name: '서울', value: 1}, 
  gungu: [
    {name: '강남구', value: 1}, 
    {name: '강동구', value: 2},
    {name: '강북구', value: 3},
    {name: '강서구', value: 4},
    {name: '관악구', value: 5},
    {name: '광진구', value: 6},
    {name: '구로구', value: 7},
    {name: '금천구', value: 8},
    {name: '노원구', value: 9},
    {name: '도봉구', value: 10},
    {name: '동대문구', value: 11},
    {name: '동작구', value: 12},
    {name: '마포구', value: 13},
    {name: '서대문구', value: 14},
    {name: '서초구', value: 15},
    {name: '성동구', value: 16},
    {name: '성북구', value: 17},
    {name: '송파구', value: 18},
    {name: '양천구', value: 19},
    {name: '영등포구', value: 20},
    {name: '용산구', value: 21},
    {name: '은평구', value: 22},
    {name: '종로구', value: 23},
    {name: '중구', value: 24},
    {name: '중랑구', value: 25},
  ]}, {
  si: {name: '인천', value: 2}, 
  gungu: [
    {name: '강화군', value: 1}, 
    {name: '계양구', value: 2},
    {name: '미추홀구', value: 3},
    {name: '남동구', value: 4},
    {name: '동구', value: 5},
    {name: '부평구', value: 6},
    {name: '서구', value: 7},
    {name: '연수구', value: 8},
    {name: '옹진군', value: 9},
    {name: '중구', value: 10},
  ]}, {
  si: {name: '대전', value: 3}, 
  gungu: [
    {name: '대덕구', value: 1}, 
    {name: '동구', value: 2},
    {name: '서구', value: 3},
    {name: '유성구', value: 4},
    {name: '중구', value: 5},
  ]}, {
  si: {name: '대구', value: 4}, 
  gungu: [
    {name: '남구', value: 1}, 
    {name: '달서구', value: 2},
    {name: '달성군', value: 3},
    {name: '동구', value: 4},
    {name: '북구', value: 5},
    {name: '서구', value: 6},
    {name: '수성구', value: 7},
    {name: '중구', value: 8},
  ]}, {
  si: {name: '광주', value: 5}, 
  gungu: [
    {name: '광산구', value: 1}, 
    {name: '남구', value: 2},
    {name: '동구', value: 3},
    {name: '북구', value: 4},
    {name: '서구', value: 5},
  ]}, {
  si: {name: '부산', value: 6}, 
  gungu: [
    {name: '강서구', value: 1}, 
    {name: '금정구', value: 2},
    {name: '기장군', value: 3},
    {name: '남구', value: 4},
    {name: '동구', value: 5},
    {name: '동래구', value: 6},
    {name: '부산진구', value: 7},
    {name: '북구', value: 8},
    {name: '사상구', value: 9},
    {name: '사하구', value: 10},
    {name: '서구', value: 11},
    {name: '수영구', value: 12},
    {name: '연제구', value: 13},
    {name: '영도구', value: 14},
    {name: '중구', value: 15},
    {name: '해운대구', value: 16},
  ]}, {
  si: {name: '울산', value: 7}, 
  gungu: [
    {name: '중구', value: 1}, 
    {name: '남구', value: 2},
    {name: '동구', value: 3},
    {name: '북구', value: 4},
    {name: '울주군', value: 5},
  ]}, {
  si: {name: '세종특별자치시', value: 8}, 
  gungu: [
    {name: '세종특별자치시', value: 1}, 
  ]}, {
  si: {name: '경기도', value: 31}, 
  gungu: [
    {name: '가평군', value: 1}, 
    {name: '고양시', value: 2},
    {name: '과천시', value: 3},
    {name: '광명시', value: 4},
    {name: '광주시', value: 5},
    {name: '구리시', value: 6},
    {name: '군포시', value: 7},
    {name: '김포시', value: 8},
    {name: '남양주시', value: 9},
    {name: '동두천시', value: 10},
    {name: '부천시', value: 11},
    {name: '성남시', value: 12},
    {name: '수원시', value: 13},
    {name: '시흥시', value: 14},
    {name: '안산시', value: 15},
    {name: '안성시', value: 16},
    {name: '안양시', value: 17},
    {name: '양주시', value: 18},
    {name: '양평군', value: 19},
    {name: '여주시', value: 20},
    {name: '연천군', value: 21},
    {name: '오산시', value: 22},
    {name: '용인시', value: 23},
    {name: '의왕시', value: 24},
    {name: '의정부시', value: 25},
    {name: '이천시', value: 26},
    {name: '파주시', value: 27},
    {name: '평택시', value: 28},
    {name: '포천시', value: 29},
    {name: '하남시', value: 30},
    {name: '화성시', value: 31},
  ]}, {
  si: {name: '강원도', value: 32}, 
  gungu: [
    {name: '강릉시', value: 1}, 
    {name: '고성군', value: 2},
    {name: '동해시', value: 3},
    {name: '삼척시', value: 4},
    {name: '속초시', value: 5},
    {name: '양구군', value: 6},
    {name: '양양군', value: 7},
    {name: '영월군', value: 8},
    {name: '원주시', value: 9},
    {name: '인제군', value: 10},
    {name: '정선군', value: 11},
    {name: '철원군', value: 12},
    {name: '춘천시', value: 13},
    {name: '태백시', value: 14},
    {name: '평창군', value: 15},
    {name: '홍천군', value: 16},
    {name: '화천군', value: 17},
    {name: '횡성군', value: 18},
  ]}, {
  si: {name: '충청북도', value: 33}, 
  gungu: [
    {name: '괴산군', value: 1}, 
    {name: '단양군', value: 2},
    {name: '보은군', value: 3},
    {name: '영동군', value: 4},
    {name: '옥천군', value: 5},
    {name: '음성군', value: 6},
    {name: '제천시', value: 7},
    {name: '진천군', value: 8},
    {name: '청원군', value: 9},
    {name: '청주시', value: 10},
    {name: '충주시', value: 11},
    {name: '증평군', value: 12},
  ]}, {
  si: {name: '충청남도', value: 34}, 
  gungu: [
    {name: '공주시', value: 1}, 
    {name: '금산군', value: 2},
    {name: '논산시', value: 3},
    {name: '당진시', value: 4},
    {name: '보령시', value: 5},
    {name: '부여군', value: 6},
    {name: '서산시', value: 7},
    {name: '서천군', value: 8},
    {name: '아산시', value: 9},
    {name: '예산군', value: 11},
    {name: '천안시', value: 12},
    {name: '청양군', value: 13},
    {name: '태안군', value: 14},
    {name: '홍성군', value: 15},
    {name: '계룡시', value: 16},
  ]}, {
  si: {name: '경상북도', value: 35}, 
  gungu: [
    {name: '경산시', value: 1}, 
    {name: '경주시', value: 2},
    {name: '고령군', value: 3},
    {name: '구미시', value: 4},
    {name: '군위군', value: 5},
    {name: '김천시', value: 6},
    {name: '문경시', value: 7},
    {name: '봉화군', value: 8},
    {name: '상주시', value: 9},
    {name: '성주군', value: 10},
    {name: '안동시', value: 11},
    {name: '영덕군', value: 12},
    {name: '영양군', value: 13},
    {name: '영주시', value: 14},
    {name: '영천시', value: 15},
    {name: '예천군', value: 16},
    {name: '울릉군', value: 17},
    {name: '울진군', value: 18},
    {name: '의성군', value: 19},
    {name: '청도군', value: 20},
    {name: '청송군', value: 21},
    {name: '칠곡군', value: 22},
    {name: '포항시', value: 23},
  ]}, {
  si: {name: '경상남도', value: 36}, 
  gungu: [
    {name: '거제시', value: 1}, 
    {name: '거창군', value: 2},
    {name: '고성군', value: 3},
    {name: '김해시', value: 4},
    {name: '남해군', value: 5},
    {name: '마산시', value: 6},
    {name: '밀양시', value: 7},
    {name: '사천시', value: 8},
    {name: '산청군', value: 9},
    {name: '양산시', value: 10},
    {name: '의령군', value: 12},
    {name: '진주시', value: 13},
    {name: '진해시', value: 14},
    {name: '창녕군', value: 15},
    {name: '창원시', value: 16},
    {name: '통영시', value: 17},
    {name: '하동군', value: 18},
    {name: '함안군', value: 19},
    {name: '함양군', value: 20},
    {name: '합천군', value: 21},
  ]}, {
  si: {name: '전라북도', value: 37}, 
  gungu: [
    {name: '고창군', value: 1}, 
    {name: '군산시', value: 2},
    {name: '김제시', value: 3},
    {name: '남원시', value: 4},
    {name: '무주군', value: 5},
    {name: '부안군', value: 6},
    {name: '순창군', value: 7},
    {name: '완주군', value: 8},
    {name: '익산시', value: 9},
    {name: '임실군', value: 10},
    {name: '장수군', value: 11},
    {name: '전주시', value: 12},
    {name: '정읍시', value: 13},
    {name: '진안군', value: 14},
  ]}, {
  si: {name: '전라남도', value: 38}, 
  gungu: [
    {name: '강진군', value: 1}, 
    {name: '고흥군', value: 2},
    {name: '곡성군', value: 3},
    {name: '광양시', value: 4},
    {name: '구례군', value: 5},
    {name: '나주시', value: 6},
    {name: '담양군', value: 7},
    {name: '목포시', value: 8},
    {name: '무안군', value: 9},
    {name: '보성군', value: 10},
    {name: '순천시', value: 11},
    {name: '신안군', value: 12},
    {name: '여수시', value: 13},
    {name: '영광군', value: 16},
    {name: '영암군', value: 17},
    {name: '완도군', value: 18},
    {name: '장성군', value: 19},
    {name: '장흥군', value: 20},
    {name: '진도군', value: 21},
    {name: '함평군', value: 22},
    {name: '해남군', value: 23},
    {name: '화순군', value: 24},
  ]}, {
  si: {name: '제주도', value: 39}, 
  gungu: [
    {name: '남제주군', value: 1}, 
    {name: '북제주군', value: 2},
    {name: '서귀포시', value: 3},
    {name: '제주시', value: 4},
  ]}
]
  


  export default sigungu